/**
 * tailwind.config.ts
 * Exact color, typography, spacing, and border-radius system from the Stitch design.
 * Extends Tailwind's defaults — do not remove any keys here without updating components.
 */
import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-background": "#1a1b21",
        "on-secondary-fixed": "#261900",
        "on-primary-fixed": "#00164e",
        "on-surface-variant": "#444652",
        "on-tertiary-fixed": "#1b1c1a",
        "inverse-surface": "#2f3036",
        "secondary": "#7b5800",
        "surface": "#faf8ff",
        "surface-tint": "#3d59af",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#b5c4ff",
        "secondary-fixed-dim": "#f4be4f",
        "on-surface": "#1a1b21",
        "surface-container-low": "#f4f3fb",
        "secondary-fixed": "#ffdea4",
        "surface-variant": "#e3e1e9",
        "on-primary-fixed-variant": "#224095",
        "surface-container-high": "#e8e7ef",
        "surface-bright": "#faf8ff",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#464744",
        "error-container": "#ffdad6",
        "on-primary-container": "#91a9ff",
        "primary-container": "#1a3a8f",
        "on-tertiary-container": "#adada9",
        "tertiary-fixed": "#e4e2de",
        "inverse-on-surface": "#f1f0f8",
        "tertiary-fixed-dim": "#c8c6c3",
        "secondary-container": "#fdc656",
        "primary": "#00236f",
        "on-secondary-container": "#735200",
        "error": "#ba1a1a",
        "inverse-primary": "#b5c4ff",
        "tertiary": "#2a2b29",
        "primary-fixed": "#dce1ff",
        "on-secondary-fixed-variant": "#5d4200",
        "on-secondary": "#ffffff",
        "outline": "#757683",
        "surface-container-highest": "#e3e1e9",
        "outline-variant": "#c4c5d3",
        "surface-container": "#eeedf5",
        "surface-dim": "#dad9e1",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#40413e",
        "background": "#fafaf8",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "24px",
        "max-width": "1280px",
        "margin-desktop": "64px",
        base: "8px",
        "margin-mobile": "20px",
      },
      fontFamily: {
        "label-mono": ["JetBrains Mono", "monospace"],
        "headline-lg": ["DM Sans", "sans-serif"],
        "headline-md": ["DM Sans", "sans-serif"],
        "display-hero-mobile": ["Playfair Display", "serif"],
        "body-md": ["DM Sans", "sans-serif"],
        "display-hero": ["Playfair Display", "serif"],
        "body-lg": ["DM Sans", "sans-serif"],
      },
      fontSize: {
        "label-mono": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "display-hero-mobile": ["44px", { lineHeight: "52px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-hero": ["72px", { lineHeight: "84px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
} satisfies Config;
